### ISSUE TITLE
Running GenerateWorldBindings.fsx results in error.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#454]
Lately, I've just been pasting the script into Program.fs to regenerate WorldBindings.fs. The error that occurs is the following -

```
Binding session to 'C:\Development\Nu\Nu\Nu\../../Nu/Nu/bin/Debug/net7.0/Nu.dll'...
System.TypeInitializationException: The type initializer for 'Nu.Constants.GameTime' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$Nu>.$GameTime' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
File name: 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at <StartupCode$Nu>.$GameTime..cctor()
   --- End of inner exception stack trace ---
   at Nu.Constants.GameTime..cctor()
   --- End of inner exception stack trace ---
   at Nu.Constants.GameTime.get_DesiredFrameRate()
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in C:\Development\Nu\Nu\Nu\GenerateWorldBindings.fsx:line 409
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

I presume this is at least tangentially related to this open issue - https://github.com/dotnet/fsharp/issues/12703

**Comment by bryanedds** [comment]
Also, genworldbindings is now in an even more broken state due to recent changes. Let's at least fix those up.

**Comment by bryanedds** [comment]
File removed since NuScript was removed.
