### ISSUE TITLE
Project Run Error on Manjaro Linux

### ISSUE THREAD

**Issue by kevinkleine** [bryanedds/Nu#599]
Hi there,

F# noob here, trying to run a sample on Manjaro Linux. I have .NET 6 and 7 installed. When executing "dotnet run" in the Projects/Elmario subfolder I get the following error output:

```
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: profile 'ICC Profile': 'GRAY': Gray color space not permitted on RGB PNG
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
Process terminated. Assertion Failed
2023-10-10 14:43:05.0553|Trace|Failed to load static model 'Assets/Default/HighlightModel.obj' due to: Could not load static model 'Assets/Default/HighlightModel.obj' due to: "Assimp.AssimpException: Error loading unmanaged library from path: libassimp.so
   at Assimp.Unmanaged.UnmanagedLinuxLibc6LibraryImplementation.NativeLoadLibrary(String path) in C:\Development\assimpnet\AssimpNet\Unmanaged\Platforms\UnmanagedLinuxLibc6LibraryImplementation.cs:line 64
   at Assimp.Unmanaged.UnmanagedLibraryImplementation.LoadLibrary(String path) in C:\Development\assimpnet\AssimpNet\Unmanaged\UnmanagedLibraryImplementation.cs:line 115
   at Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary(String libPath) in C:\Development\assimpnet\AssimpNet\Unmanaged\UnmanagedLibrary.cs:line 200
   at Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary() in C:\Development\assimpnet\AssimpNet\Unmanaged\UnmanagedLibrary.cs:line 168
   at Assimp.Unmanaged.UnmanagedLibrary.LoadIfNotLoaded() in C:\Development\assimpnet\AssimpNet\Unmanaged\UnmanagedLibrary.cs:line 256
   at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore() in C:\Development\assimpnet\AssimpNet\Unmanaged\AssimpLibrary.cs:line 372
   at Assimp.AssimpContext.CreateConfigs() in C:\Development\assimpnet\AssimpNet\AssimpContext.cs:line 1089
   at Assimp.AssimpContext.PrepareImport() in C:\Development\assimpnet\AssimpNet\AssimpContext.cs:line 1107
   at Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags) in C:\Development\assimpnet\AssimpNet\AssimpContext.cs:line 288
   at OpenGL.PhysicallyBased.TryCreatePhysicallyBasedStaticModel(Boolean renderable, String filePath, PhysicallyBasedMaterial defaultMaterial, TextureMemo textureMemo, AssimpContext assimp) in /home/kevin/p/k/fsharp/nu/Nu/Nu/OpenGL/OpenGL.PhysicallyBased.fs:line 893"
   at Nu.Log.trace(String message) in /home/kevin/p/k/fsharp/nu/Nu/Nu/Core/Log.fs:line 65
   at Nu.MetadataModule.tryGenerateStaticModelMetadata[a](Asset`1 asset) in /home/kevin/p/k/fsharp/nu/Nu/Nu/Metadata/Metadata.fs:line 81
   at Nu.MetadataModule.tryGenerateAssetMetadata[a](Asset`1 asset) in /home/kevin/p/k/fsharp/nu/Nu/Nu/Metadata/Metadata.fs:line 109
   at Nu.MetadataModule.Pipe #1 stage #1 at line 130@130.Invoke(Asset`1 asset)
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/local.fs:line 236
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/local.fs:line 246
   at Microsoft.FSharp.Collections.ListModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) in /build/dotnet-core/src/sources/src/fsharp/artifacts/source-build/self/src/src/FSharp.Core/list.fs:line 97
   at Nu.MetadataModule.tryGenerateMetadataPackage(TConfig config, String packageName, AssetGraph assetGraph) in /home/kevin/p/k/fsharp/nu/Nu/Nu/Metadata/Metadata.fs:line 130
   at Nu.MetadataModule.generateMetadata(Boolean imperative, AssetGraph assetGraph) in /home/kevin/p/k/fsharp/nu/Nu/Nu/Metadata/Metadata.fs:line 141
   at Nu.WorldModule3.World.tryMake.Static(SdlDeps sdlDeps, WorldConfig config, NuPlugin plugin) in /home/kevin/p/k/fsharp/nu/Nu/Nu/World/World.fs:line 596
   at Nu.WorldModule3.World.run.Static(WorldConfig worldConfig, NuPlugin plugin) in /home/kevin/p/k/fsharp/nu/Nu/Nu/World/World.fs:line 718
   at Elmario.Program.main(String[] _arg1) in /home/kevin/p/k/fsharp/nu/Projects/Elmario/Program.fs:line 26
   ```

**Comment by bryanedds** [comment]
Hi!

If you haven't yet, please follow the steps to setting up Nu here - https://github.com/bryanedds/Nu/wiki/Getting-Started-with-Nu

In particular, it looks like you didn't do step 5 - `If you're on Linux, install the OS-level dependencies by running the Configure.Linux.Development.sh shell script found in Nu's root folder.`

**Comment by kevinkleine** [comment]
There is a package "dl" installed on my system, but I don't think it's the one that the code is referring to: https://aur.archlinux.org/packages/dl

**Comment by bryanedds** [comment]
There was a similar issue here - https://github.com/bryanedds/Nu/issues/590

Not sure if it's related it, but it's some bullshit that seems to come up on linux a lot.

**Comment by bryanedds** [comment]
Any update with this? I'll assumed this is solve and close this if I don't hear back.

**Comment by bryanedds** [comment]
Closed assuming resolved. Please re-open if closed in error! :)
