### ISSUE TITLE
Engine exception in BlazeVector

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#765]
This occurred while editing individual Sections group files and reloading code in the editor -

```
2024-04-01 17:35:29.922 -04:00|Info|Initialized SDL 2.28.5.
2024-04-01 17:35:32.020 -04:00|Info|Initialized OpenGL 4.1.0 NVIDIA 546.33.
2024-04-01 17:35:37.609 -04:00|Info|Loading Render2d package 'Gameplay' for asset 'SkylineTileSet' on the fly.
2024-04-01 17:35:37.611 -04:00|Info|Loading Audio package 'Gameplay' for asset 'DeadBlaze' on the fly.
2024-04-01 17:35:53.666 -04:00|Info|Inspecting directory C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../.. for F# code...
2024-04-01 17:35:53.670 -04:00|Info|Inspecting code for F# project 'C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../..\BlazeVector.fsproj'...
2024-04-01 17:35:53.673 -04:00|Info|Compiling code via generated F# script:
#r "nuget: Csv, 2.0.93"
#r "nuget: DotRecast.Recast.Toolset, 2024.1.3"
#r "nuget: FParsec, 1.1.1"
#r "nuget: Aether.Physics2D, 2.0.0"
#r "nuget: Magick.NET-Q8-AnyCPU, 13.5.0"
#r "nuget: Pfim, 0.11.2"
#r "nuget: Prime, 9.20.2"
#r "nuget: System.Configuration.ConfigurationManager, 8.0.0"
#r "nuget: System.Drawing.Common, 8.0.0"
#r "nuget: Twizzle.ImGuizmo.NET, 1.89.4.1"
#r "../../../../../Nu/Nu.Dependencies/AssimpNet/netstandard1.3/AssimpNet.dll"
#r "../../../../../Nu/Nu.Dependencies/BulletSharpPInvoke/netstandard2.1/BulletSharp.dll"
#r "../../../../../Nu/Nu.Dependencies/OpenGL.NET/lib/netcoreapp2.2/OpenGL.Net.dll"
#r "../../../../../Nu/Nu.Dependencies/SDL2-CS/netstandard2.0/SDL2-CS.dll"
#r "../../../../../Nu/Nu.Dependencies/TiledSharp/lib/netstandard2.0/TiledSharp.dll"
#r "../../../../../Nu/Nu.Math/bin/Debug/netstandard2.0/Nu.Math.dll"
#r "../../../../../Nu/Nu.Pipe/bin/Debug/net7.0/Nu.Pipe.dll"
#r "../../../../../Nu/Nu/bin/Debug/net7.0/Nu.dll"
#load "../../../Assets.fs"
#load "../../../Simulants.fs"
#load "../../../Events.fs"
#load "../../../Bullet.fs"
#load "../../../Enemy.fs"
#load "../../../Player.fs"
#load "../../../Gameplay.fs"
#load "../../../BlazeVector.fs"
#load "../../../BlazeVectorPlugin.fs"
2024-04-01 17:35:57.052 -04:00|Info|Code compiled with no warnings.
2024-04-01 17:35:57.053 -04:00|Info|Updating code...
2024-04-01 17:35:57.081 -04:00|Info|Code updated.
2024-04-01 17:36:35.163 -04:00|Info|Loading Audio package 'Gui' for asset 'Machinery' on the fly.
2024-04-01 17:37:05.417 -04:00|Info|Inspecting directory C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../.. for F# code...
2024-04-01 17:37:05.420 -04:00|Info|Inspecting code for F# project 'C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../..\BlazeVector.fsproj'...
2024-04-01 17:37:05.422 -04:00|Info|Compiling code via generated F# script:
#r "nuget: Csv, 2.0.93"
#r "nuget: DotRecast.Recast.Toolset, 2024.1.3"
#r "nuget: FParsec, 1.1.1"
#r "nuget: Aether.Physics2D, 2.0.0"
#r "nuget: Magick.NET-Q8-AnyCPU, 13.5.0"
#r "nuget: Pfim, 0.11.2"
#r "nuget: Prime, 9.20.2"
#r "nuget: System.Configuration.ConfigurationManager, 8.0.0"
#r "nuget: System.Drawing.Common, 8.0.0"
#r "nuget: Twizzle.ImGuizmo.NET, 1.89.4.1"
#r "../../../../../Nu/Nu.Dependencies/AssimpNet/netstandard1.3/AssimpNet.dll"
#r "../../../../../Nu/Nu.Dependencies/BulletSharpPInvoke/netstandard2.1/BulletSharp.dll"
#r "../../../../../Nu/Nu.Dependencies/OpenGL.NET/lib/netcoreapp2.2/OpenGL.Net.dll"
#r "../../../../../Nu/Nu.Dependencies/SDL2-CS/netstandard2.0/SDL2-CS.dll"
#r "../../../../../Nu/Nu.Dependencies/TiledSharp/lib/netstandard2.0/TiledSharp.dll"
#r "../../../../../Nu/Nu.Math/bin/Debug/netstandard2.0/Nu.Math.dll"
#r "../../../../../Nu/Nu.Pipe/bin/Debug/net7.0/Nu.Pipe.dll"
#r "../../../../../Nu/Nu/bin/Debug/net7.0/Nu.dll"
#load "../../../Assets.fs"
#load "../../../Simulants.fs"
#load "../../../Events.fs"
#load "../../../Bullet.fs"
#load "../../../Enemy.fs"
#load "../../../Player.fs"
#load "../../../Gameplay.fs"
#load "../../../BlazeVector.fs"
#load "../../../BlazeVectorPlugin.fs"
2024-04-01 17:37:06.677 -04:00|Info|Code compiled with no warnings.
2024-04-01 17:37:06.678 -04:00|Info|Updating code...
2024-04-01 17:37:06.686 -04:00|Info|Code updated.
2024-04-01 17:38:05.049 -04:00|Info|Inspecting directory C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../.. for F# code...
2024-04-01 17:38:05.053 -04:00|Info|Inspecting code for F# project 'C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../..\BlazeVector.fsproj'...
2024-04-01 17:38:05.054 -04:00|Info|Compiling code via generated F# script:
#r "nuget: Csv, 2.0.93"
#r "nuget: DotRecast.Recast.Toolset, 2024.1.3"
#r "nuget: FParsec, 1.1.1"
#r "nuget: Aether.Physics2D, 2.0.0"
#r "nuget: Magick.NET-Q8-AnyCPU, 13.5.0"
#r "nuget: Pfim, 0.11.2"
#r "nuget: Prime, 9.20.2"
#r "nuget: System.Configuration.ConfigurationManager, 8.0.0"
#r "nuget: System.Drawing.Common, 8.0.0"
#r "nuget: Twizzle.ImGuizmo.NET, 1.89.4.1"
#r "../../../../../Nu/Nu.Dependencies/AssimpNet/netstandard1.3/AssimpNet.dll"
#r "../../../../../Nu/Nu.Dependencies/BulletSharpPInvoke/netstandard2.1/BulletSharp.dll"
#r "../../../../../Nu/Nu.Dependencies/OpenGL.NET/lib/netcoreapp2.2/OpenGL.Net.dll"
#r "../../../../../Nu/Nu.Dependencies/SDL2-CS/netstandard2.0/SDL2-CS.dll"
#r "../../../../../Nu/Nu.Dependencies/TiledSharp/lib/netstandard2.0/TiledSharp.dll"
#r "../../../../../Nu/Nu.Math/bin/Debug/netstandard2.0/Nu.Math.dll"
#r "../../../../../Nu/Nu.Pipe/bin/Debug/net7.0/Nu.Pipe.dll"
#r "../../../../../Nu/Nu/bin/Debug/net7.0/Nu.dll"
#load "../../../Assets.fs"
#load "../../../Simulants.fs"
#load "../../../Events.fs"
#load "../../../Bullet.fs"
#load "../../../Enemy.fs"
#load "../../../Player.fs"
#load "../../../Gameplay.fs"
#load "../../../BlazeVector.fs"
#load "../../../BlazeVectorPlugin.fs"
2024-04-01 17:38:06.280 -04:00|Info|Code compiled with no warnings.
2024-04-01 17:38:06.282 -04:00|Info|Updating code...
2024-04-01 17:38:06.299 -04:00|Info|Code updated.
2024-04-01 17:38:38.203 -04:00|Info|Inspecting directory C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../.. for F# code...
2024-04-01 17:38:38.206 -04:00|Info|Inspecting code for F# project 'C:/Development/Nu/Projects/BlazeVector/bin/Debug/net7.0/../../..\BlazeVector.fsproj'...
2024-04-01 17:38:38.208 -04:00|Info|Compiling code via generated F# script:
#r "nuget: Csv, 2.0.93"
#r "nuget: DotRecast.Recast.Toolset, 2024.1.3"
#r "nuget: FParsec, 1.1.1"
#r "nuget: Aether.Physics2D, 2.0.0"
#r "nuget: Magick.NET-Q8-AnyCPU, 13.5.0"
#r "nuget: Pfim, 0.11.2"
#r "nuget: Prime, 9.20.2"
#r "nuget: System.Configuration.ConfigurationManager, 8.0.0"
#r "nuget: System.Drawing.Common, 8.0.0"
#r "nuget: Twizzle.ImGuizmo.NET, 1.89.4.1"
#r "../../../../../Nu/Nu.Dependencies/AssimpNet/netstandard1.3/AssimpNet.dll"
#r "../../../../../Nu/Nu.Dependencies/BulletSharpPInvoke/netstandard2.1/BulletSharp.dll"
#r "../../../../../Nu/Nu.Dependencies/OpenGL.NET/lib/netcoreapp2.2/OpenGL.Net.dll"
#r "../../../../../Nu/Nu.Dependencies/SDL2-CS/netstandard2.0/SDL2-CS.dll"
#r "../../../../../Nu/Nu.Dependencies/TiledSharp/lib/netstandard2.0/TiledSharp.dll"
#r "../../../../../Nu/Nu.Math/bin/Debug/netstandard2.0/Nu.Math.dll"
#r "../../../../../Nu/Nu.Pipe/bin/Debug/net7.0/Nu.Pipe.dll"
#r "../../../../../Nu/Nu/bin/Debug/net7.0/Nu.dll"
#load "../../../Assets.fs"
#load "../../../Simulants.fs"
#load "../../../Events.fs"
#load "../../../Bullet.fs"
#load "../../../Enemy.fs"
#load "../../../Player.fs"
#load "../../../Gameplay.fs"
#load "../../../BlazeVector.fs"
#load "../../../BlazeVectorPlugin.fs"
2024-04-01 17:38:39.552 -04:00|Info|Code compiled with no warnings.
2024-04-01 17:38:39.553 -04:00|Info|Updating code...
2024-04-01 17:38:39.561 -04:00|Info|Code updated.
Fail: 2024-04-01 17:41:16.502 -04:00|Trace|"System.Exception: Could not find entity 'Game/Gameplay/Layer/@2628'.
   at Nu.WorldModuleEntity.World.getEntityState.Static(Entity entity, World world) in C:\Development\Nu\Nu\Nu\World\WorldModuleEntity.fs:line 142
   at Nu.WorldModuleEntity.World.getEntityAlwaysUpdate.Static(Entity entity, World world) in C:\Development\Nu\Nu\Nu\World\WorldModuleEntity.fs:line 359
   at Nu.WorldEntityModule.Entity.GetAlwaysUpdate(Entity this, World world) in C:\Development\Nu\Nu\Nu\World\WorldEntity.fs:line 207
   at Nu.WorldModule2.world@1270-188.Invoke(World world, Quadelement`1 element) in C:\Development\Nu\Nu\Nu\World\WorldModule2.fs:line 1271
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in D:\a\_work\1\s\src\FSharp.Core\seq.fs:line 914
   at Nu.WorldModule2.World.updateSimulants.Static(World world) in C:\Development\Nu\Nu\Nu\World\WorldModule2.fs:line 1269
   at Nu.WorldModule2.World.runWithoutCleanUp.Static(FSharpFunc`2 runWhile, FSharpFunc`2 preProcess, FSharpFunc`2 perProcess, FSharpFunc`2 postProcess, FSharpFunc`2 imGuiProcess, FSharpFunc`2 imGuiPostProcess, Liveness liveness, Boolean firstFrame, World world) in C:\Development\Nu\Nu\Nu\World\WorldModule2.fs:line 1572
   at Nu.WorldModule2.World.runWithCleanUp.Static(FSharpFunc`2 runWhile, FSharpFunc`2 preProcess, FSharpFunc`2 perProcess, FSharpFunc`2 postProcess, FSharpFunc`2 imGuiProcess, FSharpFunc`2 imGuiPostProcess, Liveness liveness, Boolean firstFrame, World world) in C:\Development\Nu\Nu\Nu\World\WorldModule2.fs:line 1733"
```

**Comment by bryanedds** [comment]
Also likely unrelated, also getting a likely incorrect tile layer strip calculation, perhaps due to precision error -

![image](https://github.com/bryanedds/Nu/assets/1625560/f76a8517-d762-45ec-a5a3-a424a3919025)

**Comment by bryanedds** [comment]
Chalking this up to an issue with an intermediate commit scenario as I can't repro.
