### ISSUE TITLE
Add support for old integrated graphics

### ISSUE THREAD

**Issue by asik** [bryanedds/Nu#839]
I'm trying to run this on my potato Intel HD 4400 integrated graphics, and can't make it past https://github.com/bryanedds/Nu/blob/2bb9fd8d9a4dd909b8404cd075e9256f92f9f667/Nu/Nu/OpenGL/OpenGL.Hl.fs#L123 . I tried commenting it out but then it still fails later. 
![image](https://github.com/user-attachments/assets/a57dfbe5-4223-4467-884e-f1d23711f830)

I can run Monogame and Godot and I was interested in trying this but I don't have access to a better GPU at the moment, so I guess this is a feature request to support older GPUs.

**Comment by bryanedds** [comment]
Can you tell me what's in the `message` variable so I can see what the actual error is on your end?

**Comment by asik** [comment]
Sure, it's:

> "2024-08-02 13:39:12.124 +08:00|Debug|API_ID_RECOMPILE_FRAGMENT_SHADER performance warning has been generated. Fragment shader recompiled due to state change."

**Comment by bryanedds** [comment]
I believe that's a warning, not an error. What happens when you run past it? Also, does your card actually support OpenGL 4.1?

**Comment by asik** [comment]
Hm that's interesting. In Debug if I just F5 through all the warnings I can run it fine. But if I run without attaching a debugger, it crashes.

> 2024-08-02 13:44:14.618 +08:00|Info|Initialized SDL 2.28.5.
2024-08-02 13:44:15.706 +08:00|Info|Initialized OpenGL 4.1.0 - Build 20.19.15.5126.
Process terminated. Assertion Failed
2024-08-02 13:44:16.569 +08:00|Debug|API_ID_RECOMPILE_FRAGMENT_SHADER performance warning has been generated. Fragment shader recompiled due to state change.
   at Nu.Log.debug(String message) in C:\dev\Nu\Nu\Nu\Core\Log.fs:line 77
   at OpenGL.Hl.DebugMessageListener(DebugSource _arg4, DebugType _arg3, UInt32 _arg2, DebugSeverity severity, Int32 length, IntPtr message, IntPtr _arg1) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.Hl.fs:line 50
   at OpenGL.Hl.DebugMessageProc@57.Invoke(DebugSource delegateArg0, DebugType delegateArg1, UInt32 delegateArg2, DebugSeverity delegateArg3, Int32 delegateArg4, IntPtr delegateArg5, IntPtr delegateArg6)
   at OpenGL.Gl.DrawElements(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices) in C:\Development\OpenGL.Net\OpenGL.Net\Gl.VERSION_1_1.cs:line 1171
   at OpenGL.CubeMap.DrawCubeMap(Single[] view, Single[] projection, Texture cubeMap, CubeMapGeometry geometry, CubeMapShader shader) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.CubeMap.fs:line 291
   at OpenGL.LightMap.CreateIrradianceMap(Int32 resolution, CubeMapShader irradianceShader, CubeMapSurface cubeMapSurface) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.LightMap.fs:line 182
   at Nu.GlRenderer3d.make(IntPtr glContext, Window window) in C:\dev\Nu\Nu\Nu\Render\Renderer3d.fs:line 3222
   at Nu.RendererThread.Run(ImFontAtlasPtr fonts, FSharpOption`1 windowOpt) in C:\dev\Nu\Nu\Nu\Render\RendererProcess.fs:line 330
   at <StartupCode$Nu>.$RendererProcess.thread@419-1.Invoke() in C:\dev\Nu\Nu\Nu\Render\RendererProcess.fs:line 419
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)


C:\dev\Nu\Projects\Elmario\bin\Debug\net8.0\Elmario.exe (process 7632) exited with code -2146232797.
Press any key to close this window . . .

The Intel HD Graphics Control Panel says my GPU supports OpenGL 4.3.

**Comment by bryanedds** [comment]
Ya, shutting down the app is the expected behavior when we call Trace.Fail. And I believe the reason we call that is because anisotropic filtering is an explicit requirement of Nu. You didn't comment out that check, correct?

Perhaps we go too hard with the used of Trace.Fail in some cases... Let me know the answer to the above question and maybe we can make a quick policy change to get you up and running in all run modes!

**Comment by asik** [comment]
This is with the anisotropic filtering check commented out.

**Comment by bryanedds** [comment]
As, so trace is getting called via opengl assert as well. Yes, let me fix this up engine-wide and get back to you in about 5 minutes.

**Comment by bryanedds** [comment]
Alright, if you pull latest, these problems should be addressed!

**Comment by asik** [comment]
Thanks! I can now get past the anisotropic filtering warning without having to comment it out, but it still crashes when I CTRL-F5 (run without debugger attached).

> 2024-08-02 14:40:03.209 +08:00|Info|Initialized SDL 2.28.5.
2024-08-02 14:40:04.390 +08:00|Info|Initialized OpenGL 4.1.0 - Build 20.19.15.5126.
Elmario Error: 0 : 2024-08-02 14:40:04.394 +08:00|Trace|Anisotropic texture filtering required to properly run Nu.
Process terminated. Assertion Failed
2024-08-02 14:40:05.220 +08:00|Debug|API_ID_RECOMPILE_FRAGMENT_SHADER performance warning has been generated. Fragment shader recompiled due to state change.
   at Nu.Log.debug(String message) in C:\dev\Nu\Nu\Nu\Core\Log.fs:line 77
   at OpenGL.Hl.DebugMessageListener(DebugSource _arg4, DebugType _arg3, UInt32 _arg2, DebugSeverity severity, Int32 length, IntPtr message, IntPtr _arg1) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.Hl.fs:line 50
   at OpenGL.Hl.DebugMessageProc@57.Invoke(DebugSource delegateArg0, DebugType delegateArg1, UInt32 delegateArg2, DebugSeverity delegateArg3, Int32 delegateArg4, IntPtr delegateArg5, IntPtr delegateArg6)
   at OpenGL.Gl.DrawElements(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices) in C:\Development\OpenGL.Net\OpenGL.Net\Gl.VERSION_1_1.cs:line 1171
   at OpenGL.CubeMap.DrawCubeMap(Single[] view, Single[] projection, Texture cubeMap, CubeMapGeometry geometry, CubeMapShader shader) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.CubeMap.fs:line 291
   at OpenGL.LightMap.CreateIrradianceMap(Int32 resolution, CubeMapShader irradianceShader, CubeMapSurface cubeMapSurface) in C:\dev\Nu\Nu\Nu\OpenGL\OpenGL.LightMap.fs:line 182
   at Nu.GlRenderer3d.make(IntPtr glContext, Window window) in C:\dev\Nu\Nu\Nu\Render\Renderer3d.fs:line 3222
   at Nu.RendererThread.Run(ImFontAtlasPtr fonts, FSharpOption`1 windowOpt) in C:\dev\Nu\Nu\Nu\Render\RendererProcess.fs:line 330
   at <StartupCode$Nu>.$RendererProcess.thread@419-1.Invoke() in C:\dev\Nu\Nu\Nu\Render\RendererProcess.fs:line 419
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)


C:\dev\Nu\Projects\Elmario\bin\Debug\net8.0\Elmario.exe (process 18128) exited with code -2146232797.
Press any key to close this window . . .

**Comment by bryanedds** [comment]
Maybe Debug.Fail also causes an exit? I'll change that as well and ask you to try again.

**Comment by bryanedds** [comment]
This all points to an issue with the logging systems design. I'll attempt to fix and get back to you quickly.

**Comment by bryanedds** [comment]
Alright, please give it another shot and let me know if it's been adddressed!

**Comment by asik** [comment]
Looks like it works! Thanks a lot!
