### ISSUE TITLE
Linux rendering issues.

### ISSUE THREAD

**Issue by reinux** [bryanedds/Nu#857]
![image](https://github.com/user-attachments/assets/2e6dafe9-abc0-4240-80e2-f9d65d7a2157)

![image](https://github.com/user-attachments/assets/f3437098-57a5-45ae-8302-2fbf1c6bf88a)

As usual, on Linux. As usual, I can just work on Windows.

**Comment by bryanedds** [comment]
According to our convo in chat, this is happening on a different, more mainstream linux environment. I'm definitely going to need more details on what that environment actually consists of in order to verify this issue directly.

**Comment by bryanedds** [comment]
This is tested and working on NVidia 535 Linux, so the issues is either specific to AMD or your environment. AMD Windows is also working fine, btw.

**Comment by reinux** [comment]
So far:

- Windows AMD is okay, though Terra Firma still runs rather slowly
- AMD Linux still showing symptoms
- Nvidia Linux null ref exception on startup again with both Gaia and Terra Firma

Removing "ATI Technologies Inc." from `Render.VendorNamesExceptedFromGlFinishSwapRequirement` still yielded the glFinish warning, so I checked what it was actually returning ("AMD") and added that to the list instead. That turned off the warning, but the problem persists.

Some info regarding the nvidia situation:
```
[I] rei@oden ~/source/nu/Nu/Nu.Gaia (master)> dotnet run
2024-08-27 16:48:56.389 -07:00|Info|Initialized SDL 2.30.5.
2024-08-27 16:48:56.803 -07:00|Info|Slow path used to load texture metadata.
2024-08-27 16:48:57.225 -07:00|Info|Initialized OpenGL 4.1.0 NVIDIA 560.35.03.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenGL.Gl.DebugMessageControl(DebugSource source, DebugType type, DebugSeverity severity, UInt32[] ids, Boolean enabled) in C:\Development\OpenGL.Net\OpenGL.Net\Gl.VERSION_4_3.cs:line 3967
   at OpenGL.Hl.AttachDebugMessageCallback() in /home/rei/source/nu/Nu/Nu/OpenGL/OpenGL.Hl.fs:line 67
   at OpenGL.Hl.InitContext() in /home/rei/source/nu/Nu/Nu/OpenGL/OpenGL.Hl.fs:line 116
   at Nu.RendererThread.Run(ImFontAtlasPtr fonts, FSharpOption`1 windowOpt) in /home/rei/source/nu/Nu/Nu/Render/RendererProcess.fs:line 328
   at <StartupCode$Nu>.$RendererProcess.thread@423-1.Invoke() in /home/rei/source/nu/Nu/Nu/Render/RendererProcess.fs:line 423
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[I] rei@oden ~/source/nu/Nu/Nu.Gaia (master) [SIGABRT]> nvidia-smi
Tue Aug 27 16:56:23 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:06:00.0  On |                  Off |
| 32%   37C    P0             59W /  450W |    6646MiB /  24564MiB |     64%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3351      G   /run/wrappers/bin/kwin_wayland               1684MiB |
|    0   N/A  N/A      3582      G   /run/current-system/sw/bin/Xwayland             8MiB |
|    0   N/A  N/A      3612      G   ...lasma-workspace-6.1.4/bin/ksmserver          6MiB |
|    0   N/A  N/A      3614      G   ...5xmvw5ac7g1mqj-kded-6.5.0/bin/kded6          6MiB |
|    0   N/A  N/A      3648      G   ...sma-workspace-6.1.4/bin/plasmashell       1095MiB |
|    0   N/A  N/A      3653      G   ...erd-6.1.4/libexec/kactivitymanagerd          6MiB |
|    0   N/A  N/A      3656      G   ...c/polkit-kde-authentication-agent-1          6MiB |
|    0   N/A  N/A      3657      G   ...il-6.1.4/libexec/org_kde_powerdevil          6MiB |
|    0   N/A  N/A      3658      G   ....1.4/libexec/xdg-desktop-portal-kde          6MiB |
|    0   N/A  N/A      3817      G   ...connect-kde-24.08.0/bin/kdeconnectd          6MiB |
|    0   N/A  N/A      3827      G   /run/current-system/sw/bin/kaccess              6MiB |
|    0   N/A  N/A      3833      G   /run/current-system/sw/bin/kalendarac           6MiB |
|    0   N/A  N/A      4220      G   ...yeDropper --variations-seed-version         27MiB |
|    0   N/A  N/A      4371      G   ...e2986b0ce2a7941b75593493e0087193e5b       1406MiB |
|    0   N/A  N/A      4795      G   ...yOnDemand --variations-seed-version        170MiB |
|    0   N/A  N/A      8241      G   ...erProcess --variations-seed-version         68MiB |
|    0   N/A  N/A     10164      G   ...urrent-system/sw/bin/systemsettings         84MiB |
|    0   N/A  N/A     14306      G   /etc/profiles/per-user/rei/bin/kitty           34MiB |
|    0   N/A  N/A     20775      G   ...-plasma-workspace-6.1.4/bin/krunner         16MiB |
|    0   N/A  N/A     20812      G   ...workspace-6.1.4/libexec/baloorunner          6MiB |
|    0   N/A  N/A     24384      G   /etc/profiles/per-user/rei/bin/kitty           52MiB |
+-----------------------------------------------------------------------------------------+
```

AMD unfortunately doesn't have an nvidia-smi equivalent, so all I can really tell you is that it's a Radeon 780M running on KDE Plasma Wayland with OpenGL 4.6 (Core Profile) Mesa 24.1.5 and SDL 2.30.5. Aside from GPU-specific libraries and configs, it's the exact same build of the OS and environment as the Nvidia.

**Comment by bryanedds** [comment]
Since you've got the NRE bug with NV again, sounds like you need to figure out what the environment fix you did on the other machine and post it here.

Overall. this again sounds like Wayland not providing proper support for GL via SDL2 and because of that, I don't think there's anything actionable from our end with the current information.

Marking this as Linux / Investigation as it's simply not our bug.

**Comment by reinux** [comment]
The environment variable that did it was `QT_WAYLAND_DISABLE_WINDOWDECORATION=0` (i.e. disabling it). It's disabled now, so it's something else this time.

That said, I agree that unless there are other users that depend on Linux support at this moment, we ought to leave it for now.

**Comment by reinux** [comment]
Just set up my system to make it easier to switch between X and Wayland, and tested on KDE on X11 on AMD. Same problem. So it's not a Wayland thing on AMD.

**Comment by bryanedds** [comment]
Since AMD isn't throwing a NullReferenceException, I think that would classify it as a different issue. For AMD, it's probably the MESA driver which is known to never have worked well for OpenGL for us. In that case, could you try installing actual AMD drivers and seeing what happens?

**Comment by bryanedds** [comment]
For the AMD Linux + MESA issues, maybe obtaining a donor computer for my local test bench is the way forward. I've assigned a task for such in Trello.

**Comment by bryanedds** [comment]
As it turns out, 2D and 3D rendering is working fine on my AMD Linux. also, interestingly, SSR is also working fine here, too. So it seems like it's another situation where your specific environment is causing some sort of specific set of issues.

For the NVidia+Wayland issue, you should attempt to debug that from your end since it at least gives you some information via the NullReferenceException. You shouldn't have to spend much time learning OpenGL I wouldn't think because the problem simply sounds like it's OpenGL not initializing properly.

For your AMD+X11 issue, maybe give the latest Unbuntu out-of-box installation a shot on your AMD machine. I know Unbuntu isn't the best for your use other user cases, but it could at least give us some better information that what we have now.

Also for NVidia, MESA drivers tend to lag behind on recently released hardware, so maybe that's the case for your NV 4090?

I'm chalking both of these up to your specific linux configurations as we now have proof that the do work at least on out-of-the-box Ubuntu installs. If you feel like this is a satisfactory response, go ahead and close the issue and work on it as an local environment problem.

**Comment by reinux** [comment]
Could you do me a favor and check which driver/OpenGL version Ubuntu is running? I wonder if I may need to roll back to a specific version.

**Comment by bryanedds** [comment]
I'm using the version of Mesa that comes with the latest out-of-box Ubuntu 24.04.1, which is reported as -

Mesa 24.0.9-0ubuntu0.1

Kind of a strange version name, but whatever.

**Comment by bryanedds** [comment]
Oh and I believe it's running Core profile OpenGL 4.5 (which is fine since we only request 4.1).

**Comment by reinux** [comment]
Success on nvidia 560.35.03!

Two changes:

- libx11 needs to be brought in explicitly on both Wayland and X (surprisingly not the case on AMD)
- Need to use the proprietary driver as opposed to the now-default open source driver

The open source driver is said to be nearly as complete as the proprietary driver as of 560, but there are a handful of known issues. It's unfortunate that the NRE is the only error it could produce. Maybe if more people have this issue, we can look for a way to dig up more useful error messages.

AMD is still producing those artifacts. Wouldn't surprise me if it's driver-side.

**Comment by bryanedds** [comment]
Any follow up on this on the AMD side? I know Project 5 was running well for you, but I'm not sure if that was on Nvidia.

**Comment by bryanedds** [comment]
Closing this due to lack of follow-up. Reopen if needed!
